runtime: python

env: flex
entrypoint: gunicorn -b :$PORT main:app
# entrypoint: gunicorn -b :$PORT -w 4 main:app


runtime_config:
  python_version: 3



resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1.0
